apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content-blue
  namespace: bluegreen
data:
  index.html: |
    <html>
      <head><title>Blue</title></head>
      <body style="font-family: Arial;">
        <h1>Blue Version âœ…</h1>
        <p>Deployed via Kubernetes Blue-Green strategy.</p>
      </body>
    </html>
